// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimpchatWeb.Services.Db.Contexts.Default;

#nullable disable

namespace SimpchatWeb.Migrations
{
    [DbContext(typeof(SimpchatDbContext))]
    [Migration("20251008103639_RenameColumnsGroupProfileUrlAndChannelProfileUrlToProfilePictureUrl")]
    partial class RenameColumnsGroupProfileUrlAndChannelProfileUrlToProfilePictureUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_member_add_permission_type", new[] { "everyone", "with_conversations", "nobody" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_privacy_type", new[] { "public", "private" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "chat_type", new[] { "conversation", "group", "channel" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Channel", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Channels");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("PrivacyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Public");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatBan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("From")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatsBans");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatParticipant", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LeaveAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "ChatId");

                    b.HasIndex("ChatId");

                    b.ToTable("ChatsParticipants");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("character varying(85)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ChatPermissions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatUserPermission", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "ChatId", "PermissionId");

                    b.HasIndex("ChatId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ChatsUsersPermissions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(85)
                        .HasColumnType("character varying(85)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalPermissions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalRoles");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("GlobalRolesPermissions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRoleUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UsersGlobalRoles");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("MediaUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("ReplyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.HasKey("Id");

                    b.HasIndex("ChatId");

                    b.HasIndex("ReplyId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.MessageReaction", b =>
                {
                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReactionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ReactionId", "UserId");

                    b.HasIndex("ReactionId");

                    b.HasIndex("UserId");

                    b.ToTable("MessagesReactions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("IsSeen")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceiverId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("ChatMemberAddPermissionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(85)
                        .HasColumnType("character varying(85)")
                        .HasDefaultValue("");

                    b.Property<DateTimeOffset>("LastSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP AT TIME ZONE 'UTC'");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Channel", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "UserCreated")
                        .WithMany("Channels")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithOne("Channel")
                        .HasForeignKey("SimpchatWeb.Services.Db.Contexts.Default.Entities.Channel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("UserCreated");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatBan", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithMany("Bans")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "User")
                        .WithMany("ChatBans")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatParticipant", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithMany("Participants")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "User")
                        .WithMany("ChatsParticipated")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatUserPermission", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithMany("ParticipantsPermissions")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatPermission", "Permission")
                        .WithMany("UsersAppliedTo")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "User")
                        .WithMany("ChatPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Conversation", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithOne("Conversation")
                        .HasForeignKey("SimpchatWeb.Services.Db.Contexts.Default.Entities.Conversation", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRolePermission", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalPermission", "Permission")
                        .WithMany("GlobalRoles")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRole", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRoleUser", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "User")
                        .WithMany("GlobalRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Group", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "UserCreated")
                        .WithMany("Groups")
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithOne("Group")
                        .HasForeignKey("SimpchatWeb.Services.Db.Contexts.Default.Entities.Group", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("UserCreated");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", "ReplyTo")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyId");

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "Sender")
                        .WithMany("Messages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("ReplyTo");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.MessageReaction", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", "Message")
                        .WithMany("Reactions")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Reaction", "Reaction")
                        .WithMany("MessagesAppliedTo")
                        .HasForeignKey("ReactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "User")
                        .WithMany("MessageReactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Reaction");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Notification", b =>
                {
                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", "Message")
                        .WithMany("Notifications")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", "Receiver")
                        .WithMany("Notifications")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Chat", b =>
                {
                    b.Navigation("Bans");

                    b.Navigation("Channel")
                        .IsRequired();

                    b.Navigation("Conversation")
                        .IsRequired();

                    b.Navigation("Group")
                        .IsRequired();

                    b.Navigation("Messages");

                    b.Navigation("Participants");

                    b.Navigation("ParticipantsPermissions");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.ChatPermission", b =>
                {
                    b.Navigation("UsersAppliedTo");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalPermission", b =>
                {
                    b.Navigation("GlobalRoles");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.GlobalRole", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Message", b =>
                {
                    b.Navigation("Notifications");

                    b.Navigation("Reactions");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.Reaction", b =>
                {
                    b.Navigation("MessagesAppliedTo");
                });

            modelBuilder.Entity("SimpchatWeb.Services.Db.Contexts.Default.Entities.User", b =>
                {
                    b.Navigation("Channels");

                    b.Navigation("ChatBans");

                    b.Navigation("ChatPermissions");

                    b.Navigation("ChatsParticipated");

                    b.Navigation("GlobalRoles");

                    b.Navigation("Groups");

                    b.Navigation("MessageReactions");

                    b.Navigation("Messages");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
