namespace SimpchatWeb.Services.GlobalEnums
{
    public enum GlobalPermissions
    {
        //<User>/<Moderator>/<Admin>
        UpdateOwnProfile,
        SendMessage,
        UpdateOwnMessage,
        JoinGroup,
        JoinChannel,
        JoinConversation,
        SearchUser,
        CreateGroup,
        UpdateOwnGroup,
        CreateChannel,
        UpdateOwnChannel,
        CreateConversation,
        SendFriendRequest,
        AcceptFriendRequest,
        BlockFriend,
        AcceptFriend,
        PendFriendRequest,
        GiveReaction,
        //<User>/<Moderator>/<Admin>
        //<Moderator>/<Admin>
        UpdateAnyGroupBasics,
        UpdateAnyChannelBasics,
        BanUserTemporary,
        BanUserFromAnyGroup,
        BanUserFromAnyChannel,
        IgnoreBlockFromUser,
        //<Moderator>/<Admin>
        //<Admin>
        BanUserPermanently,
        UnblockAnyUser,
        UpdateAnyGroup,
        UpdateAnyChannel,
        DeleteAnyGroup,
        DeleteAnyChannel,
        DeleteAnyUser,
        UpdateAnyUser,
        DeleteAnyConversation,
        DeleteAnyFriendship,
        DeleteAnyMessage,
        UpdateAnyMessage,
        PinAnyMessage,
        BlockAnyFriendship,
        IgnoreGroupRestrictions,
        IgnoreChannelRestrictions
        //<Admin>
    }
}
